/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.54
 * Generated at: 2021-11-11 09:49:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.tutee;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Member;

public final class tuteeMyClass_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	Member loginUser = (Member)session.getAttribute("loginUser");
	/* Tutor tutor = (Tutor)session.getAttribute("tutor"); */

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>My Classroom</title>\r\n");
      out.write("<script src=\"js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/menubar.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/tuteeMyClass.css\">\r\n");
      out.write("<style>\r\n");
      out.write("	#logBtn{\r\n");
      out.write("		/* 임시로 상단바의 로그인버튼 폰트 적용 */\r\n");
      out.write("		font-family: monospace;\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"app-dashboard shrink-medium\">\r\n");
      out.write("	\r\n");
      out.write("		<!-- 상단바 -->\r\n");
      out.write("		<div class=\"row expanded app-dashboard-top-nav-bar\">\r\n");
      out.write("			<div class=\"columns medium-2\">\r\n");
      out.write("				<a class=\"app-dashboard-logo\" href=\"");
      out.print( request.getContextPath() );
      out.write("\"><img\r\n");
      out.write("					src=\"images/logo.png\" width=\"70px\" height=\"55px\"></a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"columns shrink app-dashboard-top-bar-actions\">\r\n");
      out.write("							<div class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/myInfo.me\"><img src=\"images/myPage.png\"></a></div> <!-- 마이페이지아이콘 -->\r\n");
      out.write("							<div class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/contact.co\"><img src=\"images/contact.png\"></a></div> <!-- 콘택트아이콘 -->\r\n");
      out.write("							<div class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/myClass.me\"><img src=\"images/like.png\"></a></div> <!-- 찜아이콘  -->\r\n");
      out.write("							\r\n");
      out.write("							");
 if(loginUser == null) { 
      out.write("\r\n");
      out.write("								<div class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/loginForm.me\"><button id=\"logBtn\">Login</button></a></div> <!-- 로그인 -->\r\n");
      out.write("							");
 } else { 
      out.write("\r\n");
      out.write("								<div class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/logout.me\"><button id=\"logBtn\">LogOut</button></a></div> <!-- 로그아웃 -->\r\n");
      out.write("							");
 } 
      out.write("\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("				<!-- <button href=\"#\" class=\"button hollow\">Logout</button> 로그아웃 버튼 -->\r\n");
      out.write("				<!-- <a href=\"#\" height=\"30\" width=\"30\" alt=\"\"><i class=\"fa fa-info-circle\"></i></a> -->\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div class=\"app-dashboard-body off-canvas-wrapper\">\r\n");
      out.write("			<div id=\"app-dashboard-sidebar\"\r\n");
      out.write("				class=\"app-dashboard-sidebar position-left off-canvas off-canvas-absolute reveal-for-medium\"\r\n");
      out.write("				data-off-canvas>\r\n");
      out.write("				<div class=\"app-dashboard-sidebar-title-area\">\r\n");
      out.write("					<div class=\"app-dashboard-close-sidebar\">\r\n");
      out.write("						<!-- Close button -->\r\n");
      out.write("						<button id=\"close-sidebar\" data-app-dashboard-toggle-shrink\r\n");
      out.write("							class=\"app-dashboard-sidebar-close-button show-for-medium\"\r\n");
      out.write("							aria-label=\"Close menu\" type=\"button\">\r\n");
      out.write("							<span aria-hidden=\"true\"><a href=\"#\"><i\r\n");
      out.write("									class=\"large fa fa-angle-double-left\"><img\r\n");
      out.write("								src=\"images/three-dots-vertical.svg\"></i></a></span> \r\n");
      out.write("						</button>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- open button -->\r\n");
      out.write("					<div class=\"app-dashboard-open-sidebar\">\r\n");
      out.write("						<button id=\"open-sidebar\" data-app-dashboard-toggle-shrink\r\n");
      out.write("							class=\"app-dashboard-open-sidebar-button show-for-medium\"\r\n");
      out.write("							aria-label=\"open menu\" type=\"button\">\r\n");
      out.write("							<span aria-hidden=\"true\"><a href=\"#\"><i\r\n");
      out.write("									class=\"large fa fa-angle-double-right\"><img\r\n");
      out.write("								src=\"images/three-dots-vertical.svg\"></i></a></span> \r\n");
      out.write("						</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- 사이드바 -->\r\n");
      out.write("				<div class=\"app-dashboard-sidebar-inner\">\r\n");
      out.write("					<ul class=\"menu vertical\">\r\n");
      out.write("						<li><a href=\"#\">\r\n");
      out.write("							<span class=\"app-dashboard-sidebar-text\"><h3>나의 클래스룸</h3></span> <!-- 누르면 나의 클래스룸 -> 수강중/수강완료/찜한클래스/후기 전체 볼 수 있는 페이지 -->\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li><a href=\"#\">\r\n");
      out.write("							<span class=\"app-dashboard-sidebar-text\">수강중인 클래스</span> <!-- 누르면 수강중인 클래스 페이지로 이동(페이지 따로 만들기) -->\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li><a href=\"#\"> \r\n");
      out.write("							<span class=\"app-dashboard-sidebar-text\">수강완료 클래스</span> <!-- 누르면 수강완료 클래스 페이지로 이동 -->\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li><a href=\"#\"> \r\n");
      out.write("							<span class=\"app-dashboard-sidebar-text\">찜한 클래스</span> <!-- 누르면 찜한 클래스 페이지로 이동 -->\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li><a href=\"#\"> \r\n");
      out.write("							<span class=\"app-dashboard-sidebar-text\">내가 쓴 후기</span> <!-- 누르면 내가 쓴 후기 페이지로 이동 -->\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<br>\r\n");
      out.write("						<li><a href=\"\"> \r\n");
      out.write("							<span class=\"app-dashboard-sidebar-text\"><h3>내 정보</h3></span> <!-- 내 정보 조회 페이지  -->\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li><a href=\"\"> \r\n");
      out.write("							<span class=\"app-dashboard-sidebar-text\">내 정보 수정</span> <!--  내 정보 수정 페이지-->\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li><a href=\"\"> \r\n");
      out.write("							<span class=\"app-dashboard-sidebar-text\">결제정보</span>  \r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li><a href=\"\"> \r\n");
      out.write("							<span class=\"app-dashboard-sidebar-text\">튜티 탈퇴</span>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<br><br><br>\r\n");
      out.write("						\r\n");
      out.write("						");
      out.write("\r\n");
      out.write("						");
 if(loginUser != null && loginUser.getGrade().equals("B")) { 
      out.write(' ');
      out.write(' ');
      out.write("\r\n");
      out.write("						<li>\r\n");
      out.write("							<span class=\"app-dashboard-sidebar-text\"><h3>튜터</h3></span> \r\n");
      out.write("						</li>\r\n");
      out.write("						<li ><a href=\"\"> \r\n");
      out.write("							<span class=\"app-dashboard-sidebar-text\">내 클래스</span>  ");
      out.write("\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li style=\"color: #9ED4C2\"><a href=\"\"> \r\n");
      out.write("							<span class=\"app-dashboard-sidebar-text\">튜터 정보</span>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li style=\"color: #9ED4C2\"><a href=\"\"> \r\n");
      out.write("							<span class=\"app-dashboard-sidebar-text\">정산하기</span>\r\n");
      out.write("						</a></li>		\r\n");
      out.write("						\r\n");
      out.write("						");
 } else { 
      out.write("\r\n");
      out.write("						<li>\r\n");
      out.write("							<span class=\"app-dashboard-sidebar-text\"><button id=\"apply-tutor-btn\">튜터 신청하기</button></span>\r\n");
      out.write("						</li> ");
      out.write("	\r\n");
      out.write("					\r\n");
      out.write("						");
 }  
      out.write("\r\n");
      out.write("						<br><br><br>\r\n");
      out.write("					</ul>\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- 본문 내용 -->\r\n");
      out.write("			<div class=\"app-dashboard-body-content off-canvas-content\"\r\n");
      out.write("				data-off-canvas-content>\r\n");
      out.write("			\r\n");
      out.write("				<!-- 수강중인 클래스 -->\r\n");
      out.write("				<h3 id=\"content1\" class=\"text-center\">수강중인 클래스</h3>\r\n");
      out.write("				<div id=\"class-room\">\r\n");
      out.write("					");
      out.write("\r\n");
      out.write("					<div class=\"card news-card\">\r\n");
      out.write("						<img src=\"images/drawing.png\">\r\n");
      out.write("						<div class=\"card-section\">\r\n");
      out.write("							<div class=\"news-card-author\">\r\n");
      out.write("								<div class=\"news-card-author-name\">\r\n");
      out.write("									<div class=\"hidden-class-no\" style=\"display: none;\">글번호</div>\r\n");
      out.write("									<a href=\"\">오일파스텔로 그리는 꽃그림</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				  ");
      out.write("\r\n");
      out.write("					<div class=\"card news-card\">\r\n");
      out.write("						<img src=\"images/drawing.png\">\r\n");
      out.write("						<div class=\"card-section\">\r\n");
      out.write("							<div class=\"news-card-author\">\r\n");
      out.write("								<div class=\"news-card-author-name\">\r\n");
      out.write("									<a href=\"#\">오일파스텔로 그리는 꽃그림</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"card news-card\">\r\n");
      out.write("						<img src=\"images/drawing.png\">\r\n");
      out.write("						<div class=\"card-section\">\r\n");
      out.write("							<div class=\"news-card-author\">\r\n");
      out.write("								<div class=\"news-card-author-name\">\r\n");
      out.write("									<a href=\"#\">오일파스텔로 그리는 꽃그림</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<br>\r\n");
      out.write("\r\n");
      out.write("				<h3 id=\"content2\">수강완료 클래스</h3>\r\n");
      out.write("				<div id=\"class-end\">\r\n");
      out.write("					<div class=\"card news-card\">\r\n");
      out.write("						<img src=\"../../images/drawing.png\">\r\n");
      out.write("						<div class=\"card-section\">\r\n");
      out.write("							<div class=\"news-card-author\">\r\n");
      out.write("								<div class=\"news-card-author-name\">\r\n");
      out.write("									<a href=\"#\">Harry Manchanda</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>	\r\n");
      out.write("						<a href=\"\"><button class=\"review-button write\">후기 작성하기</button></a>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"card news-card\">\r\n");
      out.write("						<img src=\"../../images/drawing.png\">\r\n");
      out.write("						<div class=\"card-section\">\r\n");
      out.write("							<div class=\"news-card-author\">\r\n");
      out.write("								<div class=\"news-card-author-name\">\r\n");
      out.write("									<a id=\"1\" href=\"#\">Harry Manchanda</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<a href=\"\"><button class=\"review-button write\">후기 작성하기</button></a>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("				<br>\r\n");
      out.write("\r\n");
      out.write("				<!-- 찜한 클래스 -->\r\n");
      out.write("				<h3 id=\"content3\">찜한 클래스</h3>\r\n");
      out.write("				<div id=\"class-liked\">\r\n");
      out.write("				\r\n");
      out.write("					<div class=\"card news-card\">\r\n");
      out.write("						<img src=\"images/drawing.png\">\r\n");
      out.write("						<div class=\"card-section\">\r\n");
      out.write("							<div class=\"news-card-author\">\r\n");
      out.write("								<div class=\"news-card-author-name\">\r\n");
      out.write("									<a href=\"");
      out.print( request.getContextPath() );
      out.write("/classDetail.cl\">꽃그림 클래스</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- like버튼 -->\r\n");
      out.write("						<button class=\"button button-like liked\">\r\n");
      out.write("							<i class=\"fa fa-heart\">❤</i> <!-- 아이콘 태그  -->\r\n");
      out.write("							<span>Like 취소</span>\r\n");
      out.write("						</button>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					<div class=\"card news-card\">\r\n");
      out.write("						<img src=\"../../images/drawing.png\">\r\n");
      out.write("						<div class=\"card-section\">\r\n");
      out.write("							<div class=\"news-card-author\">\r\n");
      out.write("								<div class=\"news-card-author-name\">\r\n");
      out.write("									<a href=\"#\">오일파스텔 클래스</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- like버튼 -->\r\n");
      out.write("						<button class=\"button button-like liked\">\r\n");
      out.write("							<i class=\"fa fa-heart\">❤</i> <!-- 아이콘 태그  -->\r\n");
      out.write("							<span>Like 취소</span>\r\n");
      out.write("						</button>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<br>\r\n");
      out.write("\r\n");
      out.write("				<!-- 내가 쓴 후기 -->\r\n");
      out.write("				<h3 id=\"content4\">내가 쓴 후기</h3>\r\n");
      out.write("				<div id=\"review\">\r\n");
      out.write("					<div class=\"card news-card review\">\r\n");
      out.write("						<h4>첫 수강 후기입니다</h4>\r\n");
      out.write("						<img src=\"../../images/drawing.png\">\r\n");
      out.write("						<div class=\"card-section\">\r\n");
      out.write("							<div class=\"news-card-date\">Sunday, 16th April</div>\r\n");
      out.write("							<p class=\"news-card-description\">Lorem ipsum dolor sit amet,\r\n");
      out.write("								consectetur adipisicing elit. Recusandae facere, ipsam quae sit,\r\n");
      out.write("								eaque perferendis commodi!...</p>\r\n");
      out.write("							<a href=\"review_modify.html\"><button class=\"review-button modify\">수정</button></a>\r\n");
      out.write("							<button class=\"review-button remove\">삭제</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"card news-card review\">\r\n");
      out.write("						<h4>첫 수강 후기입니다</h4>\r\n");
      out.write("						<img src=\"../../images/drawing.png\">\r\n");
      out.write("						<div class=\"card-section\">\r\n");
      out.write("							<div class=\"news-card-date\">Sunday, 16th April</div>\r\n");
      out.write("							<p class=\"news-card-description\">Lorem ipsum dolor sit amet,\r\n");
      out.write("								consectetur adipisicing elit. Recusandae facere, ipsam quae sit,\r\n");
      out.write("								eaque perferendis commodi!...</p>\r\n");
      out.write("							<a href=\"review_modify.html\"><button class=\"review-button modify\">수정</button></a>\r\n");
      out.write("							<button class=\"review-button remove\">삭제</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"card news-card review\">\r\n");
      out.write("						<h4>첫 수강 후기입니다</h4>\r\n");
      out.write("						<img src=\"../../images/drawing.png\">\r\n");
      out.write("						<div class=\"card-section\">\r\n");
      out.write("							<div class=\"news-card-date\">Sunday, 16th April</div>\r\n");
      out.write("							<p class=\"news-card-description\">Lorem ipsum dolor sit amet,\r\n");
      out.write("								consectetur adipisicing elit. Recusandae facere, ipsam quae sit,\r\n");
      out.write("								eaque perferendis commodi!...</p>\r\n");
      out.write("							<a href=\"review_modify.html\"><button class=\"review-button modify\">수정</button></a>\r\n");
      out.write("							<button class=\"review-button remove\">삭제</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"card news-card review\">\r\n");
      out.write("						<h4>첫 수강 후기입니다</h4>\r\n");
      out.write("						<img src=\"../../images/drawing.png\">\r\n");
      out.write("						<div class=\"card-section\">\r\n");
      out.write("							<div class=\"news-card-date\">Sunday, 16th April</div>\r\n");
      out.write("							<p class=\"news-card-description\">Lorem ipsum dolor sit amet,\r\n");
      out.write("								consectetur adipisicing elit. Recusandae facere, ipsam quae sit,\r\n");
      out.write("								eaque perferendis commodi!...</p>\r\n");
      out.write("							<a href=\"review_modify.html\"><button class=\"review-button modify\">수정</button></a>\r\n");
      out.write("							<button class=\"review-button remove\">삭제</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"card news-card review\">\r\n");
      out.write("						<h4>첫 수강 후기입니다</h4>\r\n");
      out.write("						<img src=\"../../images/drawing.png\">\r\n");
      out.write("						<div class=\"card-section\">\r\n");
      out.write("							<div class=\"news-card-date\">Sunday, 16th April</div>\r\n");
      out.write("							<p class=\"news-card-description\">Lorem ipsum dolor sit amet,\r\n");
      out.write("								consectetur adipisicing elit. Recusandae facere, ipsam quae sit,\r\n");
      out.write("								eaque perferendis commodi!...</p>\r\n");
      out.write("							<a href=\"review_modify.html\"><button class=\"review-button modify\">수정</button></a>\r\n");
      out.write("							<button class=\"review-button remove\">삭제</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("			<!-- FOOTER -->\r\n");
      out.write("			<footer class=\"container\" style=\"text-align: center; background: #F5F5F5;\">\r\n");
      out.write("			\r\n");
      out.write("				<p class=\"float-end\">\r\n");
      out.write("					<a href=\"#\">Back to top</a>\r\n");
      out.write("				</p>\r\n");
      out.write("				<p>\r\n");
      out.write("					&copy; 2021 HOBBYIST, Inc. &middot; <a href=\"");
      out.print( request.getContextPath() );
      out.write("/contact.co\">Contact</a>\r\n");
      out.write("					<!-- &middot; <a href=\"#\">Terms</a> -->\r\n");
      out.write("				</p>\r\n");
      out.write("			</footer> \r\n");
      out.write("	</div>\r\n");
      out.write("	<script>\r\n");
      out.write("		$(function() {\r\n");
      out.write("			// 사이드바 토글 기능\r\n");
      out.write("			$('[data-app-dashboard-toggle-shrink]').on('click',function(e) {\r\n");
      out.write("				e.preventDefault();\r\n");
      out.write("				$(this).parents('.app-dashboard').toggleClass('shrink-medium').toggleClass('shrink-large');\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			// like취소-button클릭시 찜한 클래스 삭제 기능\r\n");
      out.write("	 		$('.button-like').bind('click', function(event) {\r\n");
      out.write("				if (confirm('취소하시겠습니까?')) { // 확인 누를시에만 삭제\r\n");
      out.write("					// $(this).toggleClass(\"liked\"); //여기선 없어도 됨\r\n");
      out.write("					/* $(this).parent().remove(); */\r\n");
      out.write("					// 삭제하는 서블릿으로 이동  location.href=\"\" -> 삭제하고 다시 이 페이지로 돌아오기\r\n");
      out.write("				}\r\n");
      out.write("			}); \r\n");
      out.write("	\r\n");
      out.write("			// 후기 삭제 버튼 누를시\r\n");
      out.write("	 		$('.remove').click(function() {\r\n");
      out.write("				if (confirm('삭제하시겠습니까?')) { // 확인 누를시에만 삭제\r\n");
      out.write("					/* $(this).parent().parent().remove(); */\r\n");
      out.write("					// 삭제하는 서블릿으로 이동  location.href=\"\" -> 삭제하고 다시 이 페이지로 돌아오기\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
