/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.54
 * Generated at: 2021-11-12 15:47:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Member;

public final class loginForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<!-- 마이페이지 - 로그인 -->\r\n");
      out.write("    <meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"description\" content=\"Landing PAGE Html5 Template\">\r\n");
      out.write("    <meta name=\"keywords\" content=\"landing,startup,flat\">\r\n");
      out.write("    <meta name=\"author\" content=\"Made By GN DESIGNS\">\r\n");
      out.write("\r\n");
      out.write("    <title>로그인 페이지</title>\r\n");
      out.write("    <!-- // PLUGINS (css files) // -->\r\n");
      out.write("    <link href=\"js/plugins/bootsnav_files/skins/color.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"js/plugins/bootsnav_files/css/animate.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"js/plugins/bootsnav_files/css/bootsnav.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"js/plugins/bootsnav_files/css/overwrite.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"js/plugins/owl-carousel/owl.carousel.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"js/plugins/owl-carousel/owl.theme.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"js/plugins/owl-carousel/owl.transitions.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"js/plugins/Magnific-Popup-master/Magnific-Popup-master/dist/magnific-popup.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!--// ICONS //-->\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!--// BOOTSTRAP & Main //-->\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/main.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<!-- 추가한 css -->\r\n");
      out.write("<style>\r\n");
      out.write(".snslogin{font-weight:bolder; color:#9ED4C2; font-size:large;}\r\n");
      out.write(".row expanded app-dashboard-top-nav-bar {backgroundcolor:black;}\r\n");
      out.write(".col-md-5{position:relative;}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!--======================================== \r\n");
      out.write("\r\n");
      out.write("           Preloader\r\n");
      out.write("\r\n");
      out.write("    ========================================-->\r\n");
      out.write("\r\n");
      out.write("<!--     <div class=\"page-preloader\"> -->\r\n");
      out.write("<!--         <div class=\"spinner\"> -->\r\n");
      out.write("<!--             <div class=\"rect1\"></div> -->\r\n");
      out.write("<!--             <div class=\"rect2\"></div> -->\r\n");
      out.write("<!--             <div class=\"rect3\"></div> -->\r\n");
      out.write("<!--             <div class=\"rect4\"></div> -->\r\n");
      out.write("<!--             <div class=\"rect5\"></div> -->\r\n");
      out.write("<!--         </div> -->\r\n");
      out.write("<!--     </div> -->\r\n");
      out.write("\r\n");
      out.write("<!-- 상단바 -->\r\n");
      out.write("\r\n");
      out.write("<!--     <div class=\"row expanded app-dashboard-top-nav-bar\"> -->\r\n");
      out.write("<!--             <div class=\"columns medium-2\"> -->\r\n");
      out.write("<!--                 <a class=\"app-dashboard-logo\" href=#><img src=\"./image/img/logo.png\" -->\r\n");
      out.write("<!--                     width=\"70px\" height=\"55px\"></a> -->\r\n");
      out.write("<!--             </div> -->\r\n");
      out.write("<!--             <div class=\"columns show-for-medium\"> -->\r\n");
      out.write("<!--                 <div class=\"app-dashboard-search-bar-container\"> -->\r\n");
      out.write("<!--                 </div> -->\r\n");
      out.write("<!--             </div> -->\r\n");
      out.write("<!--             <div class=\"columns shrink app-dashboard-top-bar-actions\"> -->\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("                \r\n");
      out.write("<!--                 로그아웃 버튼 -->\r\n");
      out.write("<!--                 <a href=\"#\" height=\"30\" width=\"30\" alt=\"\"><i -->\r\n");
      out.write("<!--                     class=\"fa fa-info-circle\"></i></a> -->\r\n");
      out.write("<!--             </div> -->\r\n");
      out.write("<!-- </div> -->\r\n");
      out.write("\r\n");
      out.write("            <!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("\r\n");
      out.write("<!--             <div class=\"collapse navbar-collapse\" id=\"navbar-menu\"> -->\r\n");
      out.write("<!--                 <ul class=\"nav navbar-nav navbar-right\"> -->\r\n");
      out.write("\r\n");
      out.write("<!--                     <li class=\"button-holder\"> -->\r\n");
      out.write("<!--                         <button type=\"button\" class=\"btn btn-blue navbar-btn\" data-toggle=\"modal\" data-target=\"#SignIn\">회원가입하기</button> -->\r\n");
      out.write("<!--                     </li> -->\r\n");
      out.write("<!--                 </ul> -->\r\n");
      out.write("<!--             </div> -->\r\n");
      out.write("            <!-- /.navbar-collapse -->\r\n");
      out.write("<!--         </div> -->\r\n");
      out.write("<!--     </nav> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!--//** Banner**//-->\r\n");
      out.write("\r\n");
      out.write("    <section id=\"home\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("            \r\n");
      out.write("                <!-- Introduction -->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-md-6 caption\">\r\n");
      out.write("                    <h1>Welcome To Hobbyist</h1>\r\n");
      out.write("                    <h2>\r\n");
      out.write("                           하비스트<span class=\"animated-text\"></span><span class=\"typed-cursor\"></span>\r\n");
      out.write("                        </h2>\r\n");
      out.write("                    <p>맞춤형 원데이 클래스 사이트</p>\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-blue btn-transparent\">Main Page로 이동</a>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Sign Up -->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-md-5 col-md-offset-1\">\r\n");
      out.write("                \r\n");
      out.write("                    <form class=\"signup-form\" action=\"");
      out.print(request.getContextPath() );
      out.write("/login.me\" method=\"post\">\r\n");
      out.write("                        <img src=\"./image/img/logogreen.png\" style=\"display: block; margin: 0 auto;\" class=\"logogreen\">\r\n");
      out.write("                        <hr>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" placeholder=\"아이디를 입력하세요\" required=\"required\" name=\"memberEmail\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <input type=\"password\" class=\"form-control\" placeholder=\"비밀번호를 입력하세요\" required=\"required\" name=\"memberPwd\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                       \r\n");
      out.write("                       <table>\r\n");
      out.write("                       <tr>\r\n");
      out.write("                        <td style=\"font-size:small; color:#9ED4C2;\">아이디/비밀번호를 잊으셨나요?</td>\r\n");
      out.write("                        <td width=\"96px\"></td>\r\n");
      out.write("                       \r\n");
      out.write("                     <td class=\"join1\" align=\"right\" style=\"color:#9ED4C2; font-weight:bold; cursor:pointer;\" onclick=\"location.href='");
      out.print( request.getContextPath());
      out.write("/joinForm.me'\">회원가입하기</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					</table>\r\n");
      out.write("                     \r\n");
      out.write("						<br>\r\n");
      out.write("                        <div class=\"form-group text-center\">\r\n");
      out.write("                        <table>\r\n");
      out.write("                        <tr height=\"100px\">\r\n");
      out.write("                            <td width=\"30%\"></td>\r\n");
      out.write("                            <td><button type=\"submit\" class=\"btn btn-blue btn-block\" style=\"background-color: #9ED4C2; width:200px; \" >로그인 하기</button>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td></td>\r\n");
      out.write("                           </tr>\r\n");
      out.write("						\r\n");
      out.write("\r\n");
      out.write("						<tr>\r\n");
      out.write("						<td></td>\r\n");
      out.write("						<td>\r\n");
      out.write("						<img src=\"./image/img/kakaologin.png\" style=\"height:50px\">\r\n");
      out.write("						</td>\r\n");
      out.write("						<td></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						</table>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!--======================================== \r\n");
      out.write("\r\n");
      out.write("           Footer\r\n");
      out.write("\r\n");
      out.write("    ========================================-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <footer>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"footer-caption\">\r\n");
      out.write("                    <img src=\"./image/img/logo.png\" class=\"img-responsive center-block\" alt=\"logo\">\r\n");
      out.write("                    <hr>\r\n");
      out.write("                    <h5 class=\"pull-left\">Vortex, &copy;2016 All rights reserved</h5>\r\n");
      out.write("                    <ul class=\"liste-unstyled pull-right\">\r\n");
      out.write("                        <li><a href=\"#twitter\"><i class=\"fa fa-twitter\"></i></a></li>\r\n");
      out.write("                        <li><a href=\"#instagram\"><i class=\"fa fa-instagram\"></i></a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Include all compiled plugins (below), or include individual files as needed -->\r\n");
      out.write("\r\n");
      out.write("    <script src=\"./js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"./js/plugins/owl-carousel/owl.carousel.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"./js/plugins/bootsnav_files/js/bootsnav.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"./js/plugins/typed.js-master/typed.js-master/dist/typed.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"./js/plugins/Magnific-Popup-master/Magnific-Popup-master/dist/jquery.magnific-popup.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"./js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
