/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.54
 * Generated at: 2021-11-12 12:23:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.classes;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Member;
import member.model.vo.Member;

public final class classDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/views/classes/../common/topbar.jsp", Long.valueOf(1636719703161L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	// 클래스에 대한 정보(ArryaList에 담아서 request에 저장한거) 가져오기

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("<title>class detail page</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/classDetail.css\">\r\n");
      out.write("<script src=\"js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<!-- datePicker -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.13.0/jquery-ui.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("	.app-dashboard-top-nav-bar{\r\n");
      out.write("		position: relative;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("/* 	 .top-bar-right {\r\n");
      out.write("	  	position: absolute;\r\n");
      out.write("	 	right: 1%;\r\n");
      out.write("	 } */\r\n");
      out.write("	\r\n");
      out.write("	.app-dashboard-top-nav-bar .menu-icon {\r\n");
      out.write("		vertical-align: text-bottom;\r\n");
      out.write("		position: relative; /* 버튼 왼쪽에 붙이기 위해 추가 */ */\r\n");
      out.write("		text-align: right; /* 상단바의 메뉴 아이콘 오른쪽으로 정렬 */\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write(" 	.app-dashboard-logo {\r\n");
      out.write("		color: #fefefe;\r\n");
      out.write("		text-transform: uppercase;\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("		margin-bottom: 15px; /* 메인페이지의 상단바의 로고 위치와 맞춤 */\r\n");
      out.write("		margin-top: 9px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("/* 	#logo{\r\n");
      out.write("		position: absolute;\r\n");
      out.write("		margin-left: 100px;\r\n");
      out.write("		margin-top: 217px;\r\n");
      out.write("		width: 300px;\r\n");
      out.write("		height: 300px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#logo-a img{\r\n");
      out.write("		height: 55px;\r\n");
      out.write("	} */\r\n");
      out.write("	\r\n");
      out.write("/* 	#menuDiv {\r\n");
      out.write("		width: 283px;\r\n");
      out.write("	} */\r\n");
      out.write("\r\n");
      out.write("	/* CDN에 설정되어 있는 columns 스타일 해제 위해 columns 클래스명 옆에 임의 클래스명을 띄어쓰기 해서 주고, 설정 바꿈, f12에서 해당 태그의 설정 확인 가능*/\r\n");
      out.write("	.topbar:last-child{\r\n");
      out.write("	    float: left;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.topbar{\r\n");
      out.write("	   width: 290px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"app-dashboard shrink-medium\">\r\n");
      out.write("	\r\n");
      out.write("		");
      out.write('\r');
      out.write('\n');

	Member loginUser = (Member)session.getAttribute("loginUser");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/menubar.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<header>\r\n");
      out.write("	  <nav>\r\n");
      out.write("		<!-- 상단바 -->\r\n");
      out.write("			<div class=\"row expanded app-dashboard-top-nav-bar\">\r\n");
      out.write("				<div class=\"topbar columns medium-2\">\r\n");
      out.write("					<a class=\"app-dashboard-logo\" href=\"");
      out.print( request.getContextPath() );
      out.write("\"><img\r\n");
      out.write("						src=\"images/logo.png\" width=\"70px\" height=\"55px\"></a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"topbar columns shrink app-dashboard-top-bar-actions\">\r\n");
      out.write("				\r\n");
      out.write("					");
 if(loginUser == null) { 
      out.write("\r\n");
      out.write("					<div class=\"nav-item\"><a class=\"nav-link\"><img src=\"images/myPage.png\" onclick=\"alert('로그인을 먼저 해주세요.');\"></a></div>\r\n");
      out.write("					");
 } else { 
      out.write("\r\n");
      out.write("					<div class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/myInfo.me\"><img src=\"images/myPage.png\"></a></div> <!-- 마이페이지아이콘 -->\r\n");
      out.write("					");
 }  
      out.write("\r\n");
      out.write("					\r\n");
      out.write("					<div class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/contact.co\"><img src=\"images/contact.png\"></a></div> <!-- 콘택트아이콘 -->\r\n");
      out.write("							\r\n");
      out.write("					");
 if(loginUser == null) { 
      out.write("\r\n");
      out.write("						<div class=\"nav-item\"><a class=\"nav-link\"><img src=\"images/like.png\" onclick=\"alert('로그인을 먼저 해주세요.');\"></a></div>\r\n");
      out.write("					");
 } else { 
      out.write("\r\n");
      out.write("						<div class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/myClass.te\"><img src=\"images/like.png\"></a></div> <!-- 찜아이콘  -->\r\n");
      out.write("					");
 }  
      out.write("\r\n");
      out.write("					\r\n");
      out.write("						\r\n");
      out.write("					");
 if(loginUser == null) { 
      out.write("\r\n");
      out.write("						<div class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/loginForm.me\"><button id=\"logBtn\">Login</button></a></div> <!-- 로그인 -->\r\n");
      out.write("					");
 } else { 
      out.write("\r\n");
      out.write("						<div class=\"nav-item\"><a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/logout.me\"><button id=\"logBtn\">Logout</button></a></div> <!-- 로그아웃 -->\r\n");
      out.write("					");
 } 
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</nav>\r\n");
      out.write("	</header>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"app-dashboard-body off-canvas-wrapper\">\r\n");
      out.write("\r\n");
      out.write("			<!-- 본문 내용 -->\r\n");
      out.write("			<div class=\"row\" style=\"margin-top: 50px;\">\r\n");
      out.write("				<div class=\"large-8 columns\"\r\n");
      out.write("					style=\"border-right: 1px solid #E3E5E8;\">\r\n");
      out.write("\r\n");
      out.write("					<article>\r\n");
      out.write("\r\n");
      out.write("						<div id=\"classTitle\" class=\"column\">\r\n");
      out.write("							<p>\r\n");
      out.write("								<img src=\"images/drawing.png\" id=\"classThumbnail\"\r\n");
      out.write("									alt=\"image for article\" alt=\"article preview image\">\r\n");
      out.write("							</p>\r\n");
      out.write("							\r\n");
      out.write("							<button class=\"button button-like\">\r\n");
      out.write("								<i class=\"fa fa-heart\">❤</i>\r\n");
      out.write("								<!-- i : 아이콘 태그 -->\r\n");
      out.write("								<span>Like</span>\r\n");
      out.write("							</button>\r\n");
      out.write("							<span style=\"font-size: xx-large; font-weight: bold;\">[Live]</span>\r\n");
      out.write("							&nbsp;&nbsp; \r\n");
      out.write("							<span style=\"font-size: xx-large; font-weight: bold;\">아이패드로 그리는 꽃그림</span>\r\n");
      out.write("\r\n");
      out.write("							<script>\r\n");
      out.write("								// like-button\r\n");
      out.write("								$(function() {\r\n");
      out.write("									$('.button-like').bind('click',\r\n");
      out.write("											function(event) {\r\n");
      out.write("												$(this).toggleClass(\"liked\");\r\n");
      out.write("											});\r\n");
      out.write("								});\r\n");
      out.write("							</script>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<hr>\r\n");
      out.write("\r\n");
      out.write("						<div  id=\"classContent\" class=\"column\">\r\n");
      out.write("\r\n");
      out.write("							<h5 style=\"font-weight: bold;\">클래스 소개</h5>\r\n");
      out.write("							<p>samplesample samplesamplesamplesample\r\n");
      out.write("								samplesamplesamplesamplesample samplesamplesamplesamplesample\r\n");
      out.write("								samplesamplesamplesamplesample\r\n");
      out.write("								samplesasamplesamplesamplesamplesample\r\n");
      out.write("								samplesamplesamplesamplesamplesamsamplesample</p>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<hr>\r\n");
      out.write("\r\n");
      out.write("						<div id=\"classImg\" class=\"column\">\r\n");
      out.write("							<h5 style=\"font-weight: bold;\">소개 사진</h5>\r\n");
      out.write("<!-- 							<p>\r\n");
      out.write("								<img src=\"../../images/pastel.png\" alt=\"image for article\"\r\n");
      out.write("									alt=\"article preview image\">\r\n");
      out.write("							</p> -->\r\n");
      out.write("\r\n");
      out.write("							<div id=\"wrapper\">\r\n");
      out.write("								<div id=\"slider-wrap\">\r\n");
      out.write("									<ul id=\"slider\">\r\n");
      out.write("										<li>\r\n");
      out.write("											<img src=\"images/pastel.png\">\r\n");
      out.write("										</li>\r\n");
      out.write("\r\n");
      out.write("										<li>\r\n");
      out.write("											<img src=\"https://fakeimg.pl/350x200/D27328/000?text=22222\">\r\n");
      out.write("										</li>\r\n");
      out.write("\r\n");
      out.write("										<li>\r\n");
      out.write("											<img src=\"https://fakeimg.pl/350x200/FF607F/000?text=33333\">\r\n");
      out.write("										</li>\r\n");
      out.write("\r\n");
      out.write("										<li>\r\n");
      out.write("											<img src=\"https://fakeimg.pl/350x200/0A6E0A/000?text=44444\">\r\n");
      out.write("										</li>\r\n");
      out.write("\r\n");
      out.write("										<li>\r\n");
      out.write("											<img src=\"https://fakeimg.pl/350x200/0064CD/000?text=55555\">\r\n");
      out.write("										</li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("									</ul>\r\n");
      out.write("\r\n");
      out.write("									<!--controls-->\r\n");
      out.write("									<div class=\"btns\" id=\"next\">\r\n");
      out.write("										<i class=\"fa fa-arrow-right\"></i>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"btns\" id=\"previous\">\r\n");
      out.write("										<i class=\"fa fa-arrow-left\"></i>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div id=\"counter\"></div>\r\n");
      out.write("\r\n");
      out.write("									<div id=\"pagination-wrap\">\r\n");
      out.write("										<ul>\r\n");
      out.write("										</ul>\r\n");
      out.write("									</div>\r\n");
      out.write("									<!--controls-->\r\n");
      out.write("\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("		\r\n");
      out.write("						<hr>\r\n");
      out.write("\r\n");
      out.write("						<div id=\"classReview\" class=\"column\">\r\n");
      out.write("							<h5 style=\"font-weight: bold;\">후기</h5> <!--4개 정도만 보여주고 더보기 클릭하면 후기 페이지로 이동 -> 해당 후기 페이지에서 페이징 처리 -->\r\n");
      out.write("							<div>\r\n");
      out.write("								<div class=\"review-section\">\r\n");
      out.write("									<h5>첫 수강 후기입니다</h5>\r\n");
      out.write("									<img class=\"review\" src=\"images/drawing.png\">\r\n");
      out.write("\r\n");
      out.write("									<div class=\"news-card-date\">Sunday, 16th April</div>\r\n");
      out.write("									<p class=\"news-card-description\">Lorem ipsum dolor sit\r\n");
      out.write("										amet, consectetur adipisicing elit. Recusandae facere, ipsam\r\n");
      out.write("										quae sit, eaque perferendis commodi!...</p>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"review-section\">\r\n");
      out.write("									<h5>두 번째 후기입니다</h5>\r\n");
      out.write("									<img class=\"review\" src=\"images/drawing.png\">\r\n");
      out.write("\r\n");
      out.write("									<div class=\"news-card-date\">Sunday, 16th April</div>\r\n");
      out.write("									<p class=\"news-card-description\">Lorem ipsum dolor sit\r\n");
      out.write("										amet, consectetur adipisicing elit. Recusandae facere, ipsam\r\n");
      out.write("										quae sit, eaque perferendis commodi!...</p>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"review-section\">\r\n");
      out.write("									<h5>세 번째 후기입니다</h5>\r\n");
      out.write("									<img class=\"review\" src=\"images/drawing.png\">\r\n");
      out.write("\r\n");
      out.write("									<div class=\"news-card-date\">Sunday, 16th April</div>\r\n");
      out.write("									<p class=\"news-card-description\">Lorem ipsum dolor sit\r\n");
      out.write("										amet, consectetur adipisicing elit. Recusandae facere, ipsam\r\n");
      out.write("										quae sit, eaque perferendis commodi!...</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							<!-- \r\n");
      out.write("					<ul class=\"pagination\" role=\"navigation\" aria-label=\"Pagination\">\r\n");
      out.write("						<li class=\"disabled\">Previous <span class=\"show-for-sr\">page</span></li>\r\n");
      out.write("						<li class=\"current\"><span class=\"show-for-sr\">You're\r\n");
      out.write("								on page</span> 1</li>\r\n");
      out.write("						<li><a href=\"#\" aria-label=\"Page 2\">2</a></li>\r\n");
      out.write("						<li><a href=\"#\" aria-label=\"Page 3\">3</a></li>\r\n");
      out.write("						<li><a href=\"#\" aria-label=\"Page 4\">4</a></li>\r\n");
      out.write("						<li><a href=\"#\" aria-label=\"Next page\">Next <span\r\n");
      out.write("								class=\"show-for-sr\">page</span></a></li>\r\n");
      out.write("					</ul> -->\r\n");
      out.write("						</div>\r\n");
      out.write("					</article>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<!-- 왼쪽 영역  -->\r\n");
      out.write("				<div class=\"large-4 columns\">\r\n");
      out.write("\r\n");
      out.write("					<aside>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<div class=\"tutor-profile\">\r\n");
      out.write("							<img src=\"images/tutor_profile.jpg\" id=\"profile-img\">\r\n");
      out.write("							<br>\r\n");
      out.write("							안녕하세요\r\n");
      out.write("							<p><span>그림공방(sample)</span>입니다</p>\r\n");
      out.write("							<p>\r\n");
      out.write("								sample튜터가 자기소개sample\r\n");
      out.write("								samplesamplesamplesam plesamplesampledfasdfdfa\r\n");
      out.write("								samplesamplesample\r\n");
      out.write("							</p>\r\n");
      out.write("							<hr style=\"background: white; height: 1px;\">\r\n");
      out.write("							<div id=\"class-info\">\r\n");
      out.write("								<p> 소요시간 : <span>2(sample)</span>시간<br></p>\r\n");
      out.write("								<p><span>1(sample)</span>~<span>8(sample)</span>명(최소인원 <span>1(sample)</span>명)</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("				\r\n");
      out.write("\r\n");
      out.write("						<br>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"apply-class\">\r\n");
      out.write("							<b>클래스 신청</b><br><br>\r\n");
      out.write("							<form action=\"\">\r\n");
      out.write("								<p>수강을 원하시는 날짜를 선택해주세요(최대 1개 선택)</p>\r\n");
      out.write("								<p>수강날짜 선택 <input type=\"text\" id=\"datepicker\" name=\"date\"></p>\r\n");
      out.write("								<br>\r\n");
      out.write("								<p>시간 선택\r\n");
      out.write("									<select>\r\n");
      out.write("										<option>18:00(sample)</option>\r\n");
      out.write("									</select>\r\n");
      out.write("								</p>\r\n");
      out.write("								<br>\r\n");
      out.write("								<div id=\"price\">\r\n");
      out.write("									<span>50,000(sample)</span>원\r\n");
      out.write("									<br><br><br>\r\n");
      out.write("									<input type=\"submit\" id=\"btnSub\" value=\"신청하기\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<br>\r\n");
      out.write("								\r\n");
      out.write("							</form>\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("					</aside>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<footer> </footer>\r\n");
      out.write("\r\n");
      out.write("			<!-- 	<script src=\"https://code.jquery.com/jquery-2.1.4.min.js\"></script>\r\n");
      out.write("			<script\r\n");
      out.write("				src=\"https://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.js\"></script>\r\n");
      out.write("			<script>\r\n");
      out.write("				$(document).foundation();\r\n");
      out.write("			</script>\r\n");
      out.write(" -->\r\n");
      out.write("		\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("<script>\r\n");
      out.write(" 	/* datepicker 관련 css */\r\n");
      out.write("	$.datepicker.setDefaults({\r\n");
      out.write("		dateFormat : 'yy-mm-dd',\r\n");
      out.write("		prevText : '이전 달',\r\n");
      out.write("		nextText : '다음 달',\r\n");
      out.write("		monthNames : [ '1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월',\r\n");
      out.write("				'10월', '11월', '12월' ],\r\n");
      out.write("		monthNamesShort : [ '1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월',\r\n");
      out.write("				'9월', '10월', '11월', '12월' ],\r\n");
      out.write("		dayNames : [ '일', '월', '화', '수', '목', '금', '토' ],\r\n");
      out.write("		dayNamesShort : [ '일', '월', '화', '수', '목', '금', '토' ],\r\n");
      out.write("		dayNamesMin : [ '일', '월', '화', '수', '목', '금', '토' ],\r\n");
      out.write("		showMonthAfterYear : true,\r\n");
      out.write("		yearSuffix : '년',\r\n");
      out.write("		buttonImageOnly : true,\r\n");
      out.write("		changeMonth : true,\r\n");
      out.write("		changeYear : true,\r\n");
      out.write("\r\n");
      out.write("		minDate : '0', // 0 넣으면 오늘날짜부터 선택할 수 있음\r\n");
      out.write("		maxDate : new Date('2021-12-1'), // 특정날짜 이후는 선택 못하게/ 기간 선택 범위 제한/ 클래스 종료일자 date를 불러와서 변수에다 값 담아 여기다 넣기\r\n");
      out.write("		showButtonPanel : true,\r\n");
      out.write("		currentText : '오늘 날짜',\r\n");
      out.write("		closeText : '닫기',\r\n");
      out.write("		showAnim : \"slide\",\r\n");
      out.write("\r\n");
      out.write("		beforeShowDay : onlyMonday, // 요일 선택 제한, 값으로 함수를 넣었음\r\n");
      out.write("		regional : \"ko\", // 지역\r\n");
      out.write("\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("	function onlyMonday(date) { // 리턴한 요일만 선택되게 하는 함수\r\n");
      out.write("		var day = date.getDay();\r\n");
      out.write("		// return [(day == 1), '']; // day == 1 월요일만 \r\n");
      out.write("		// return [(day != 0 && day != 1 && day != 3)]; // 특정 요일 제한 -> 일,월,수만 선택 안하기\r\n");
      out.write("		return [ (day == 0 || day == 1 || day == 3) ]; // 여러 요일 선택 -> 일, 월, 수 만\r\n");
      out.write("\r\n");
      out.write("		// DB에서 클래스별 가능한 요일 불러오고, 그 요일 전부  return[(day == 가능요일1 || day == 가능요일2];에 넣기 \r\n");
      out.write("		// 요일 DB에 저장될때 switch로 월은 1 화는 2 .. 일은 0 이런 식으로 클래스 별 요일 테이블에 저장되게 하기\r\n");
      out.write("	};\r\n");
      out.write("\r\n");
      out.write("	$(function() {\r\n");
      out.write("\r\n");
      out.write("		$(\"#datepicker\").datepicker();\r\n");
      out.write("\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("	$(document).ready(function() {\r\n");
      out.write("\r\n");
      out.write("		var dt = new Date()\r\n");
      out.write("\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("	/* img slide */\r\n");
      out.write("	//current position\r\n");
      out.write("	var pos = 0;\r\n");
      out.write("	//number of slides\r\n");
      out.write("	var totalSlides = $('#slider-wrap ul li').length;\r\n");
      out.write("	//get the slide width\r\n");
      out.write("	var sliderWidth = $('#slider-wrap').width();\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	$(document).ready(function(){\r\n");
      out.write("	  \r\n");
      out.write("	  \r\n");
      out.write("	  /*****************\r\n");
      out.write("	   BUILD THE SLIDER\r\n");
      out.write("	  *****************/\r\n");
      out.write("	  //set width to be 'x' times the number of slides\r\n");
      out.write("	  $('#slider-wrap ul#slider').width(sliderWidth*totalSlides);\r\n");
      out.write("	  \r\n");
      out.write("	    //next slide  \r\n");
      out.write("	  $('#next').click(function(){\r\n");
      out.write("	    slideRight();\r\n");
      out.write("	  });\r\n");
      out.write("	  \r\n");
      out.write("	  //previous slide\r\n");
      out.write("	  $('#previous').click(function(){\r\n");
      out.write("	    slideLeft();\r\n");
      out.write("	  });\r\n");
      out.write("	  \r\n");
      out.write("	  \r\n");
      out.write("	  \r\n");
      out.write("	  /*************************\r\n");
      out.write("	   //*> OPTIONAL SETTINGS\r\n");
      out.write("	  ************************/\r\n");
      out.write("	  //automatic slider\r\n");
      out.write("	  // var autoSlider = setInterval(slideRight, 3000); // 자동으로 안 넘어가게\r\n");
      out.write("	  \r\n");
      out.write("	  //for each slide \r\n");
      out.write("	  $.each($('#slider-wrap ul li'), function() { \r\n");
      out.write("	\r\n");
      out.write("	     //create a pagination\r\n");
      out.write("	     var li = document.createElement('li');\r\n");
      out.write("	     $('#pagination-wrap ul').append(li);    \r\n");
      out.write("	  });\r\n");
      out.write("	  \r\n");
      out.write("	  //counter\r\n");
      out.write("	  countSlides();\r\n");
      out.write("	  \r\n");
      out.write("	  //pagination\r\n");
      out.write("	  pagination();\r\n");
      out.write("	  \r\n");
      out.write("	  //hide/show controls/btns when hover\r\n");
      out.write("	  //pause automatic slide when hover\r\n");
      out.write("	  $('#slider-wrap').hover(\r\n");
      out.write("	    function(){ $(this).addClass('active'); clearInterval(autoSlider); }, \r\n");
      out.write("	    function(){ $(this).removeClass('active'); /* autoSlider = setInterval(slideRight, 3000); */ }\r\n");
      out.write("	  );\r\n");
      out.write("	  \r\n");
      out.write("	  \r\n");
      out.write("	\r\n");
      out.write("	});//DOCUMENT READY\r\n");
      out.write("	  \r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	/***********\r\n");
      out.write("	 SLIDE LEFT\r\n");
      out.write("	************/\r\n");
      out.write("	function slideLeft(){\r\n");
      out.write("	  pos--;\r\n");
      out.write("	  if(pos==-1){ pos = totalSlides-1; }\r\n");
      out.write("	  $('#slider-wrap ul#slider').css('left', -(sliderWidth*pos));  \r\n");
      out.write("	  \r\n");
      out.write("	  //*> optional\r\n");
      out.write("	  countSlides();\r\n");
      out.write("	  pagination();\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	/************\r\n");
      out.write("	 SLIDE RIGHT\r\n");
      out.write("	*************/\r\n");
      out.write("	function slideRight(){\r\n");
      out.write("	  pos++;\r\n");
      out.write("	  if(pos==totalSlides){ pos = 0; }\r\n");
      out.write("	  $('#slider-wrap ul#slider').css('left', -(sliderWidth*pos)); \r\n");
      out.write("	  \r\n");
      out.write("	  //*> optional \r\n");
      out.write("	  countSlides();\r\n");
      out.write("	  pagination();\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	  \r\n");
      out.write("	/************************\r\n");
      out.write("	 //*> OPTIONAL SETTINGS\r\n");
      out.write("	************************/\r\n");
      out.write("	function countSlides(){\r\n");
      out.write("	  $('#counter').html(pos+1 + ' / ' + totalSlides);\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function pagination(){\r\n");
      out.write("	  $('#pagination-wrap ul li').removeClass('active');\r\n");
      out.write("	  $('#pagination-wrap ul li:eq('+pos+')').addClass('active');\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
